-- =============================================================================
-- More platforms in the registry (public.platforms): the storefront now lists every active platform, services or not.
--
-- Additive and idempotent: existing rows are never touched (on conflict do nothing), so a platform an admin renamed, re-sorted or
-- switched off keeps its settings. A platform without services shows in the app with an empty list; a platform is switched off
-- with admin_upsert_platform(active => false).
--
-- The four adult-content sites are added SWITCHED OFF: Telegram's rules for bots and Mini Apps do not allow that kind of content,
-- so they stay hidden until an admin has decided to enable them on purpose.
-- =============================================================================

insert into public.platforms (slug, name, icon, category, sort_order, active) values
  ('whatsapp',       'WhatsApp',          'whatsapp',       'messaging', 25,  true),
  ('snapchat',       'Snapchat',          'snapchat',       'social',    110, true),
  ('linkedin',       'LinkedIn',          'linkedin',       'social',    111, true),
  ('pinterest',      'Pinterest',         'pinterest',      'social',    112, true),
  ('threads',        'Threads',           'threads',        'social',    113, true),
  ('twitch',         'Twitch',            'twitch',         'video',     114, true),
  ('vk',             'VK',                'vk',             'social',    115, true),
  ('line',           'LINE',              'line',           'messaging', 116, true),
  ('quora',          'Quora',             'quora',          'community', 117, true),
  ('tumblr',         'Tumblr',            'tumblr',         'social',    118, true),
  ('soundcloud',     'SoundCloud',        'soundcloud',     'music',     119, true),
  ('apple-music',    'Apple Music',       'apple-music',    'music',     120, true),
  ('deezer',         'Deezer',            'deezer',         'music',     121, true),
  ('audiomack',      'Audiomack',         'audiomack',      'music',     122, true),
  ('shazam',         'Shazam',            'shazam',         'music',     123, true),
  ('kick',           'Kick',              'kick',           'video',     124, true),
  ('rumble',         'Rumble',            'rumble',         'video',     125, true),
  ('trovo',          'Trovo',             'trovo',          'video',     126, true),
  ('likee',          'Likee',             'likee',          'video',     127, true),
  ('kwai',           'Kwai',              'kwai',           'video',     128, true),
  ('kuaishou',       'Kuaishou',          'kuaishou',       'video',     129, true),
  ('snackvideo',     'SnackVideo',        'snackvideo',     'video',     130, true),
  ('bluesky',        'Bluesky',           'bluesky',        'social',    131, true),
  ('truth-social',   'Truth Social',      'truth-social',   'social',    132, true),
  ('clubhouse',      'Clubhouse',         'clubhouse',      'community', 133, true),
  ('xiaohongshu',    'Xiaohongshu (RED)', 'xiaohongshu',    'social',    134, true),
  ('odnoklassniki',  'Odnoklassniki',     'odnoklassniki',  'social',    135, true),
  ('medium',         'Medium',            'medium',         'community', 136, true),
  ('steam',          'Steam',             'steam',          'community', 137, true),
  ('rutube',         'Rutube',            'rutube',         'video',     138, true),
  ('vimeo',          'Vimeo',             'vimeo',          'video',     139, true),
  ('dailymotion',    'Dailymotion',       'dailymotion',    'video',     140, true),
  ('9gag',           '9GAG',              '9gag',           'community', 141, true),
  ('jaco',           'Jaco',              'jaco',           'video',     142, true),
  ('yandex-zen',     'Yandex Zen',        'yandex-zen',     'community', 143, true),
  ('boomplay',       'Boomplay',          'boomplay',       'music',     144, true),
  ('yandex-music',   'Yandex Music',      'yandex-music',   'music',     145, true),
  ('mixcloud',       'Mixcloud',          'mixcloud',       'music',     146, true),
  ('napster',        'Napster',           'napster',        'music',     147, true),
  ('tidal',          'TIDAL',             'tidal',          'music',     148, true),
  ('spreaker',       'Spreaker',          'spreaker',       'music',     149, true),
  ('reverbnation',   'ReverbNation',      'reverbnation',   'music',     150, true),
  ('apple-podcasts', 'Apple Podcasts',    'apple-podcasts', 'music',     151, true),
  ('google-maps',    'Google Maps',       'google-maps',    'web',       152, true),
  ('yandex-maps',    'Yandex Maps',       'yandex-maps',    'web',       153, true),
  ('trustpilot',     'Trustpilot',        'trustpilot',     'web',       154, true),
  ('provenexpert',   'ProvenExpert',      'provenexpert',   'web',       155, true),
  ('tripadvisor',    'Tripadvisor',       'tripadvisor',    'web',       156, true),
  ('sitejabber',     'Sitejabber',        'sitejabber',     'web',       157, true),
  ('shopee',         'Shopee',            'shopee',         'web',       158, true),
  ('fiverr',         'Fiverr',            'fiverr',         'web',       159, true),
  ('imdb',           'IMDb',              'imdb',           'web',       160, true),
  ('github',         'GitHub',            'github',         'web',       161, true),
  ('app-store',      'App Store',         'app-store',      'web',       162, true),
  ('mobile-apps',    'Mobile Apps',       'mobile-apps',    'web',       163, true),
  ('app-installs',   'App Installs',      'app-installs',   'web',       164, true),
  ('email-marketing', 'Email Marketing',  'email-marketing', 'web',      165, true),
  ('backlinks',      'Backlinks',         'backlinks',      'web',       166, true),
  ('avito',          'Avito',             'avito',          'web',       167, true),
  ('coinmarketcap',  'CoinMarketCap',     'coinmarketcap',  'web',       168, true),
  ('crypto-nft',     'Crypto / NFT',      'crypto-nft',     'web',       169, true),
  ('roblox',         'Roblox',            'roblox',         'community', 170, true),
  ('naver',          'Naver',             'naver',          'community', 171, true),
  ('openrec',        'Openrec',           'openrec',        'video',     172, true),
  ('loco',           'Loco',              'loco',           'video',     173, true),
  ('pandatv',        'PandaTV',           'pandatv',        'video',     174, true),
  ('mixch',          'Mixch',             'mixch',          'video',     175, true),
  ('ttinglive',      'TtingLive',         'ttinglive',      'video',     176, true),
  ('topick',         'Topick',            'topick',         'community', 177, true),
  ('max',            'MAX',               'max',            'messaging', 178, true),
  ('w-tv',           'W.TV',              'w-tv',           'video',     179, true),
  ('potato',         'Potato',            'potato',         'messaging', 180, true),
  ('prime-gs',       'Prime.gs',          'prime-gs',       'video',     181, true),
  ('soop',           'SOOP',              'soop',           'video',     182, true),
  ('dribbble',       'Dribbble',          'dribbble',       'community', 183, true),
  ('periscope',      'Periscope',         'periscope',      'video',     184, true),
  ('vc-ru',          'VC.ru',             'vc-ru',          'community', 185, true),
  ('dtf',            'DTF',               'dtf',            'community', 186, true),
  ('shedevrum',      'Shedevrum',         'shedevrum',      'other',     187, true),
  ('triller',        'Triller',           'triller',        'video',     188, true),
  ('coub',           'Coub',              'coub',           'video',     189, true),
  ('multiplatform',  'Multiplatform',     'multiplatform',  'other',     190, true),
  ('smm-tools',      'SMM Tools',         'smm-tools',      'other',     191, true),
  -- hidden until an admin enables them deliberately (see the header)
  ('onlyfans',       'OnlyFans',          'onlyfans',       'social',    900, false),
  ('fansly',         'Fansly',            'fansly',         'social',    901, false),
  ('bongacams',      'BongaCams',         'bongacams',      'video',     902, false),
  ('chaturbate',     'Chaturbate',        'chaturbate',     'video',     903, false)
on conflict (slug) do nothing;
